services:
  generator:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - GIT_SHA
        - GIT_REF
    init: true
    restart: no
    working_dir: /app
    command:
      - '--database-path'
      - '/data/db.duckdb'
      - '--metadata-file'
      - '/data/mimic-cxr-2.0.0-metadata.csv'
    environment:
      LAKEFS_HOST: ${LAKEFS_HOST}
      LAKEFS_REPOSITORY: ${LAKEFS_REPOSITORY}
      LAKEFS_ACCESS_KEY_ID: ${LAKEFS_ACCESS_KEY_ID}
      LAKEFS_SECRET_ACCESS_KEY: ${LAKEFS_SECRET_ACCESS_KEY}
      DATASET_OUTPUT_DIR: /out
      DATASET_VERSION: v001
    volumes:
      - ../../mimic-iv/mimic4.duckdb:/data/db.duckdb
      - ../../mimic-cxr-jpg/mimic-cxr-2.0.0-metadata.csv:/data/mimic-cxr-2.0.0-metadata.csv
      - ./out:/out
