services:
  trainer:
    image: mmim:0.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_SHA
        - GIT_REF
    init: true
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=0
              capabilities: [gpu]
    shm_size: 8gb
    working_dir: /app
    environment:
      # only needed if local files aren't found
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}

      # URI to MLFlow server
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://host.docker.internal:5000}
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_TRACKING_USERNAME:-admin}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_TRACKING_PASSWORD:-password1234}

      # Endpoint URL for the S3-compatible storage
      DATASET_ENDPOINT_URL: ${DATASET_ENDPOINT_URL:-}
      # S3-compatible storage bucket where datasets and images are stored
      DATASET_BUCKET: ${DATASET_BUCKET:-mmim}
      # The key of the train dataset csv file. E.g.: `mimic-iv/train.csv`
      DATASET_TRAINING_KEY: ${DATASET_TRAINING_KEY:-ds_train.csv}
      # The key for the validation dataset
      DATASET_VALIDATION_KEY: ${DATASET_VALIDATION_KEY:-ds_val.csv}
      # The prefix for the images "dir" in the S3 bucket
      DATASET_IMAGES_DIR: ${DATASET_IMAGES_DIR:-mimic-cxr-jpg}
      # jpg or dcm (`.dcm` and `.jpg` are also valid)
      DATASET_IMAGES_EXTENSION: ${DATASET_IMAGES_EXTENSION:-jpg}
      # Location of the JSON file containing the dataset stats (namely mean and std)
      DATASET_STATS_FILE: ${DATASET_STATS_FILE:-/app/dataset/stats.json}

      MMIM_BATCH_SIZE: ${MMIM_BATCH_SIZE:-32}
      MMIM_EPOCHS: ${MMIM_EPOCHS:-10}
      MMIM_DROPOUT: ${MMIM_DROPOUT:-0.3}
      MMIM_LEARNING_RATE: ${MMIM_LEARNING_RATE:-0.0001}
      MMIM_TRAIN_LIMIT: ${MMIM_TRAIN_LIMIT:-1.0}
      MMIM_NUM_WORKERS: ${MMIM_NUM_WORKERS:-4}
      MMIM_DEBUG: ${MMIM_DEBUG:-false}
      # GIT_SHA: $GIT_SHA
      # GIT_REF: $GIT_REF
    volumes:
      - ../ds_train.csv:/app/dataset/ds_train.csv
      - ../ds_val.csv:/app/dataset/ds_val.csv
      - ../stats.json:/app/dataset/stats.json
      - ./dataset/mimic-cxr-jpg/physionet.org/files/mimic-cxr-jpg/2.1.0/files:/app/dataset/mimic-cxr-jpg
    extra_hosts:
      - "host.docker.internal:host-gateway"
