[project]
name = "mmim"
version = "0.1.0"
description = "Multimodal ICU Mortality prediction model"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagster>=1.13.3",
    "lakefs>=0.16.0",
    "pandas<=3.0",
]

[tool.pytest.ini_options]
testpaths = ["generator/tests", "trainer/tests"]
pythonpath = ["generator/generator", "trainer/trainer", "store/store", "."]

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "orchestrator"
registry_modules = [
    "dagster_gs.components.*",
]

[dependency-groups]
dev = [
    "mmim-generator",
    "mmim-trainer",
    "mmim-store",
    "pytest",
    "dagster-dg-cli",
    "dagster-webserver",
]

[tool.uv.sources]
mmim-generator = { path = "generator" }
mmim-trainer = { path = "trainer" }
mmim-store = { path = "store" }
