= In-hospital multimodal ICU mortality prediction

This work aims to provide a tool to estimate what the death risk is for a patient that's been just admitted in the ICU. We're therefore including data that spans from 24 hours before ICU admission (**NOT hospital admission**) to the moment of ICU admission. We predict in-hospital mortality at T=0 where T=0 is **ICU admission** (mimiciv_icu.icustays, intime column) based on all the data available to that moment.

The model is intended to be used on early ICU admission and its goal should be to help correctly prioritize resources that are usually not extensive as far as ICUs are concerned.

General rules:

* We'll be taking into account only the **first ICU admission** per patient, to avoid temporal leakage.
* In case of multiple X-rays, the closest to admission is analyzed.
* To extract the date an X-ray was taken the `study_time` field will be used, not the report timestamp.
* charttime will be used to place lab events and similar in time.
* We're not considering admission diagnosis, both because they're sometimes added later and because of human error


== Architecture
The model is a composite neural network. It's made up by:

* a **visual encoder**, whose job is to output a vector encoding of the patient conditions only based on chest X-Ray data.
* a **tabular encoder**, which encodes the patient conditions based on all the other features (vitals and lab values).
* a **fusion** model, which will have to learn to use these encodings to predict our label.


== Limitations

* Data is spot: due to hardware constraints I can't use more powerful neural networks so the model is trained on one image per patient's stay. It won't be able to evaluate "trends" or data where time is a dimension. Images a 2D only and lab test results/vitals are flattened as, tipically, `_min`, `_max`, `_mean`.
