[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "mmim-store"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "lakefs>=0.16.0",
  "pandas<3.0"
]

[dependency-groups]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["."]
namespaces = false

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
