from typing import Protocol, Any, Literal


class Loggable(Protocol):
    @property
    def model(self) -> Any: ...
    @property
    def epoch(self) -> int: ...
    @property
    def metrics(self) -> dict[str, int | float]: ...
    @property
    def metadata(self) -> dict[str, int | float | str]: ...
    @property
    def val_loss(self) -> float: ...
    @property
    def train_loss(self) -> float: ...
    @property
    def train_start_time(self) -> str: ...
    @property
    def train_end_time(self) -> str: ...
    @property
    def selection_metric(self) -> str | None: ...
    @property
    def selection_metric_value(self) -> float | int | None: ...


# completed: completed, interrupted: user interrupt, failed: handled fatal exceptions
type TrainStatus = Literal["completed", "interrupted", "failed"]


class TrainingSummary(Protocol):
    @property
    def start_time(self) -> str: ...
    @property
    def end_time(self) -> str: ...
    @property
    def train_status(self) -> TrainStatus: ...


type Hyperparameters = dict[str, int | float | str]

type Dataset = str
